@startuml
title Registere et lag i applikasjon

actor Klubb
participant Applikasjon
database API
database Database

Klubb -> Applikasjon ++ : Markerer lag medlemmer
Klubb -> Applikasjon : Trykker send
Applikasjon -> API -- : registrerMedlemmer\n(json: File, lag: String, arrangementId: int)
return Respons
API -> API: Valider data
API -> Database : Fyll data
return Respons
API --> Applikasjon : Liste med medlemmer
Applikasjon --> Klubb : visRespons(OK: bool, error)
@enduml